# Generated by Django 4.1.7 on 2023-03-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('in_stock', models.BooleanField(default=True)),
                ('condition', models.CharField(default='New', max_length=150)),
            ],
        ),
    ]
