# Generated by Django 4.1.7 on 2023-03-15 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('products_repo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.stores'),
        ),
    ]
